# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  service:
    taskfile: ./service/Taskfile.service.yml

dotenv:
  - ./service/.env.local

tasks:
  default:
    desc: List the available tasks
    cmds:
      - task --list
    silent: true

  test:
    desc: Run all the tests for the project
    cmds:
      - task: service:test

  lint:
    desc: Run all project linting.
    cmds:
      - task: service:lint
      - cmd: echo "All lint checks passed"
        silent: true